# -*- coding: utf-8 -*-
"""Referans / fallback veriler.

LIVE modda PRODUCTS/ORDERS/TRANSACTIONS Trendyol API'den senkronize edilir;
buradaki listeler yalnızca ilk-açılış seed + MOCK mod demo değerleri olarak
kullanılır."""
from datetime import datetime, timedelta

SUPPLIERS = [
    {"id": 1, "name": "Bursa Tekstil A.Ş.", "contact": "Mehmet Aydın",
     "phone": "+90 224 333 0001", "email": "siparis@bursatekstil.com",
     "on_time_rate": 0.94, "defect_rate": 0.012, "lead_time_target": 5,
     "lead_time_actual": 5.2, "total_orders": 248, "rating": 4.7,
     "city": "Bursa", "iban": "TR33 0006 1005 1978 6457 8413 26",
     "notes": "Pamuk ve karışık örme. Premium kategori."},
    {"id": 2, "name": "İzmir Ayakkabı Ltd.", "contact": "Selin Demir",
     "phone": "+90 232 444 1122", "email": "info@izmirsh.com",
     "on_time_rate": 0.78, "defect_rate": 0.045, "lead_time_target": 7,
     "lead_time_actual": 9.1, "total_orders": 122, "rating": 3.6,
     "city": "İzmir", "iban": "TR12 0001 5001 5800 7290 1234 56",
     "notes": "Deri ve spor ayakkabı. Son dönemde gecikme problemleri."},
    {"id": 3, "name": "Ankara Örme A.Ş.", "contact": "Veli Kaya",
     "phone": "+90 312 555 0099", "email": "order@ankaraorme.com",
     "on_time_rate": 0.97, "defect_rate": 0.008, "lead_time_target": 4,
     "lead_time_actual": 3.8, "total_orders": 365, "rating": 4.9,
     "city": "Ankara", "iban": "TR45 0004 6007 0488 8000 1234 78",
     "notes": "Premium tedarikçi. Aksesuar üretiminde uzman."},
    {"id": 4, "name": "İstanbul Deri A.Ş.", "contact": "Ayşe Yıldız",
     "phone": "+90 212 666 2233", "email": "satis@istderi.com",
     "on_time_rate": 0.82, "defect_rate": 0.028, "lead_time_target": 10,
     "lead_time_actual": 12.5, "total_orders": 118, "rating": 3.9,
     "city": "İstanbul", "iban": "TR67 0001 0000 0000 0000 0000 00",
     "notes": "Hakiki deri. Yüksek kalite ama tedarik süresi uzun."},
    {"id": 5, "name": "Bursa İpek A.Ş.", "contact": "Kemal Özkan",
     "phone": "+90 224 777 4455", "email": "info@bursaipek.com",
     "on_time_rate": 0.91, "defect_rate": 0.015, "lead_time_target": 6,
     "lead_time_actual": 6.4, "total_orders": 184, "rating": 4.5,
     "city": "Bursa", "iban": "TR89 0001 5000 1500 7000 1234 99",
     "notes": "İpek ve eşarp üretimi. Sezonsel."},
]

PRODUCTS = [
    {"sku": "TS-001", "name": "Premium Pamuk Tişört — Beyaz", "category": "Giyim",
     "stock": 145, "price": 249.90, "cost": 84.50, "status": "Satışta",
     "reorder_point": 50, "reorder_qty": 200, "lead_time": 5, "supplier_id": 1,
     "platforms": ["Trendyol", "Hepsiburada"], "return_rate": 0.04, "image_path": None,
     "monthly_sales": [120, 135, 98, 142, 167, 189, 210, 178, 156, 190, 245, 312],
     "weight_kg": 0.18, "barcode": "8690000000011",
     "description": "%100 ringspun pamuk, 180g/m². Anti-bakteriyel yıkamalı.",
     "color": "Beyaz", "size": "M"},
    {"sku": "TS-002", "name": "Premium Pamuk Tişört — Siyah", "category": "Giyim",
     "stock": 88, "price": 249.90, "cost": 84.50, "status": "Satışta",
     "reorder_point": 50, "reorder_qty": 200, "lead_time": 5, "supplier_id": 1,
     "platforms": ["Trendyol", "Hepsiburada"], "return_rate": 0.03, "image_path": None,
     "monthly_sales": [98, 110, 82, 124, 145, 168, 185, 156, 138, 165, 218, 280],
     "weight_kg": 0.18, "barcode": "8690000000028",
     "description": "%100 ringspun pamuk, 180g/m². Anti-bakteriyel yıkamalı.",
     "color": "Siyah", "size": "M"},
    {"sku": "SN-014", "name": "Klasik Beyaz Sneaker", "category": "Ayakkabı",
     "stock": 12, "price": 849.00, "cost": 380.00, "status": "Kritik Stok",
     "reorder_point": 30, "reorder_qty": 80, "lead_time": 7, "supplier_id": 2,
     "platforms": ["Trendyol"], "return_rate": 0.15, "image_path": None,
     "monthly_sales": [45, 52, 38, 61, 72, 89, 94, 78, 65, 70, 88, 102],
     "weight_kg": 0.85, "barcode": "8690000000035",
     "description": "Hakiki deri üst, kauçuk taban. Vintage tasarım.",
     "color": "Beyaz", "size": "42"},
    {"sku": "AK-088", "name": "Yumuşak Kışlık Bere", "category": "Aksesuar",
     "stock": 220, "price": 94.90, "cost": 31.50, "status": "Satışta",
     "reorder_point": 60, "reorder_qty": 300, "lead_time": 4, "supplier_id": 3,
     "platforms": ["Trendyol", "Hepsiburada"], "return_rate": 0.02, "image_path": None,
     "monthly_sales": [12, 8, 5, 2, 1, 0, 0, 1, 3, 45, 89, 156],
     "weight_kg": 0.08, "barcode": "8690000000042",
     "description": "Yumuşak akrilik örme, ekstra rahat bant.",
     "color": "Antrasit", "size": "Standart"},
    {"sku": "GY-101", "name": "Hakiki Deri Ceket", "category": "Giyim",
     "stock": 8, "price": 1849.00, "cost": 720.00, "status": "Kritik Stok",
     "reorder_point": 15, "reorder_qty": 40, "lead_time": 10, "supplier_id": 4,
     "platforms": ["Trendyol", "Hepsiburada"], "return_rate": 0.06, "image_path": None,
     "monthly_sales": [8, 12, 6, 4, 2, 1, 1, 3, 7, 14, 22, 18],
     "weight_kg": 1.40, "barcode": "8690000000059",
     "description": "Bikleyici dana derisi, sıvılı iç astar.",
     "color": "Siyah", "size": "L"},
    {"sku": "AK-205", "name": "İpek Desenli Fular — Lacivert", "category": "Aksesuar",
     "stock": 95, "price": 319.00, "cost": 94.50, "status": "Satışta",
     "reorder_point": 40, "reorder_qty": 150, "lead_time": 6, "supplier_id": 5,
     "platforms": ["Trendyol", "Hepsiburada"], "return_rate": 0.03, "image_path": None,
     "monthly_sales": [22, 25, 18, 30, 35, 42, 38, 32, 28, 35, 48, 62],
     "weight_kg": 0.12, "barcode": "8690000000066",
     "description": "%100 ipek, hand-rolled kenar, desenli baskı.",
     "color": "Lacivert", "size": "90x90cm"},
    {"sku": "GY-220", "name": "Slim Fit Kot Pantolon — Mavi", "category": "Giyim",
     "stock": 134, "price": 549.00, "cost": 195.00, "status": "Satışta",
     "reorder_point": 50, "reorder_qty": 200, "lead_time": 6, "supplier_id": 1,
     "platforms": ["Trendyol", "Hepsiburada"], "return_rate": 0.08, "image_path": None,
     "monthly_sales": [88, 92, 76, 105, 124, 138, 142, 128, 112, 135, 168, 198],
     "weight_kg": 0.55, "barcode": "8690000000073",
     "description": "Stretch denim, slim kalıp, yıkamalı kumaş.",
     "color": "Mavi", "size": "32/34"},
    {"sku": "AK-310", "name": "Deri Cüzdan — Kahverengi", "category": "Aksesuar",
     "stock": 58, "price": 379.00, "cost": 125.00, "status": "Satışta",
     "reorder_point": 20, "reorder_qty": 80, "lead_time": 8, "supplier_id": 4,
     "platforms": ["Trendyol"], "return_rate": 0.03, "image_path": None,
     "monthly_sales": [28, 32, 25, 38, 45, 52, 48, 42, 38, 45, 58, 72],
     "weight_kg": 0.22, "barcode": "8690000000080",
     "description": "Hakiki dana derisi, RFID korumalı, 8 kart bölmesi.",
     "color": "Kahverengi", "size": "Standart"},
    {"sku": "AK-311", "name": "Deri Kemer — Siyah", "category": "Aksesuar",
     "stock": 42, "price": 249.00, "cost": 78.00, "status": "Satışta",
     "reorder_point": 20, "reorder_qty": 80, "lead_time": 8, "supplier_id": 4,
     "platforms": ["Trendyol", "Hepsiburada"], "return_rate": 0.04, "image_path": None,
     "monthly_sales": [18, 22, 16, 24, 28, 32, 30, 26, 24, 28, 36, 45],
     "weight_kg": 0.28, "barcode": "8690000000097",
     "description": "Hakiki deri, paslanmaz çelik toka.",
     "color": "Siyah", "size": "105cm"},
    {"sku": "GY-330", "name": "Kışlık Kaban — Bej", "category": "Giyim",
     "stock": 35, "price": 1249.00, "cost": 425.00, "status": "Satışta",
     "reorder_point": 15, "reorder_qty": 50, "lead_time": 8, "supplier_id": 1,
     "platforms": ["Trendyol"], "return_rate": 0.07, "image_path": None,
     "monthly_sales": [6, 8, 4, 2, 1, 0, 0, 2, 8, 18, 34, 52],
     "weight_kg": 1.80, "barcode": "8690000000103",
     "description": "Yün karışım, suya dayanıklı, kapşonlu.",
     "color": "Bej", "size": "M"},
    {"sku": "EV-405", "name": "Pamuklu Banyo Havlu Seti", "category": "Ev",
     "stock": 112, "price": 449.00, "cost": 138.00, "status": "Satışta",
     "reorder_point": 40, "reorder_qty": 150, "lead_time": 6, "supplier_id": 5,
     "platforms": ["Trendyol", "Hepsiburada"], "return_rate": 0.02, "image_path": None,
     "monthly_sales": [32, 38, 28, 42, 48, 55, 52, 48, 42, 48, 62, 78],
     "weight_kg": 1.20, "barcode": "8690000000110",
     "description": "%100 Türk pamuğu, 600 g/m², 2 parça set.",
     "color": "Bej", "size": "70x140cm"},
    {"sku": "EV-406", "name": "Saten Çarşaf Takımı — Çift Kişi", "category": "Ev",
     "stock": 78, "price": 749.00, "cost": 245.00, "status": "Satışta",
     "reorder_point": 30, "reorder_qty": 100, "lead_time": 6, "supplier_id": 5,
     "platforms": ["Trendyol", "Hepsiburada"], "return_rate": 0.04, "image_path": None,
     "monthly_sales": [18, 22, 16, 26, 32, 38, 35, 30, 26, 32, 42, 55],
     "weight_kg": 1.85, "barcode": "8690000000127",
     "description": "Saten pamuk, anti-allerjik, 4 parça takım.",
     "color": "Antrasit", "size": "200x220"},
]

BOM = {
    "TS-001":  [("BAG-S", 1), ("LBL-STD", 1)],
    "TS-002":  [("BAG-S", 1), ("LBL-STD", 1)],
    "SN-014":  [("BAG-L", 1), ("LBL-PREM", 1), ("BOX-S", 1)],
    "AK-088":  [("BAG-S", 1), ("LBL-STD", 1)],
    "GY-101":  [("BAG-L", 1), ("LBL-PREM", 1), ("BOX-M", 1)],
    "AK-205":  [("BAG-S", 1), ("LBL-PREM", 1)],
    "GY-220":  [("BAG-M", 1), ("LBL-STD", 1)],
    "AK-310":  [("BAG-S", 1), ("LBL-PREM", 1), ("BOX-XS", 1)],
    "AK-311":  [("BAG-S", 1), ("LBL-STD", 1)],
    "GY-330":  [("BAG-L", 1), ("LBL-PREM", 1), ("BOX-M", 1)],
    "EV-405":  [("BAG-L", 1), ("LBL-STD", 1)],
    "EV-406":  [("BAG-L", 1), ("LBL-STD", 1)],
}

MATERIALS = [
    {"code": "BAG-S",    "name": "Küçük Karton Poşet",  "stock": 380,  "reorder_point": 200, "unit_cost": 1.20},
    {"code": "BAG-M",    "name": "Orta Karton Poşet",   "stock": 145,  "reorder_point": 150, "unit_cost": 1.80},
    {"code": "BAG-L",    "name": "Büyük Karton Poşet",  "stock": 240,  "reorder_point": 100, "unit_cost": 2.50},
    {"code": "BOX-XS",   "name": "XS Kutu",              "stock": 95,   "reorder_point": 60,  "unit_cost": 3.00},
    {"code": "BOX-S",    "name": "Küçük Kutu",          "stock": 60,   "reorder_point": 80,  "unit_cost": 4.50},
    {"code": "BOX-M",    "name": "Orta Kutu",           "stock": 120,  "reorder_point": 50,  "unit_cost": 6.20},
    {"code": "LBL-STD",  "name": "Standart Etiket",     "stock": 1850, "reorder_point": 500, "unit_cost": 0.25},
    {"code": "LBL-PREM", "name": "Premium Etiket",      "stock": 520,  "reorder_point": 200, "unit_cost": 0.85},
]

ORDERS = [
    {"id": "TY-99102", "platform": "Trendyol", "platform_color": "#F97316",
     "product": "Premium Pamuk Tişört — Beyaz", "sku": "TS-001", "qty": 2, "total": 499.80,
     "status": "Bekliyor", "customer": "Ahmet Yılmaz", "city": "İstanbul",
     "district": "Kadıköy", "address": "Moda Cad. No:12 D:5",
     "note": "Hediye paketi yapabilir misiniz?",
     "cargo": "Aras Kargo", "tracking": None, "est_days": 2,
     "invoice": "INV-2026-0891", "commission": 0.18, "cargo_cost": 29.99, "kdv": 0.20,
     "date": (datetime.now() - timedelta(hours=2)).strftime("%d.%m.%Y %H:%M"),
     "deadline_hours": 46,
     "tracking_url": "https://kargotakip.araskargo.com.tr/",
     "reviews": [{"user": "Ahmet Y.", "rating": 5,
                   "text": "Çok güzel ürün, hızlı geldi! Teşekkürler.", "reply": None}]},
    {"id": "HB-44231", "platform": "Hepsiburada", "platform_color": "#6366F1",
     "product": "Klasik Beyaz Sneaker", "sku": "SN-014", "qty": 1, "total": 849.00,
     "status": "Kargoda", "customer": "Fatma Kaya", "city": "Ankara",
     "district": "Çankaya", "address": "Atatürk Bul. No:45 K:3",
     "note": "",
     "cargo": "MNG Kargo", "tracking": "MNG123456789TR", "est_days": 1,
     "invoice": "INV-2026-0890", "commission": 0.14, "cargo_cost": 24.99, "kdv": 0.20,
     "date": (datetime.now() - timedelta(days=1)).strftime("%d.%m.%Y %H:%M"),
     "deadline_hours": 22,
     "tracking_url": "https://www.mngkargo.com.tr/",
     "reviews": [{"user": "Fatma K.", "rating": 2,
                   "text": "Kalıp dar geldi, bir numara büyük almalısınız.", "reply": None}]},
    {"id": "TY-99089", "platform": "Trendyol", "platform_color": "#F97316",
     "product": "Yumuşak Kışlık Bere", "sku": "AK-088", "qty": 3, "total": 284.70,
     "status": "Teslim Edildi", "customer": "Mehmet Demir", "city": "Bursa",
     "district": "Nilüfer", "address": "Çekirge Cad. No:8",
     "note": "Acele lütfen",
     "cargo": "Aras Kargo", "tracking": "ARS987654321", "est_days": 0,
     "invoice": "INV-2026-0885", "commission": 0.18, "cargo_cost": 29.99, "kdv": 0.20,
     "date": (datetime.now() - timedelta(days=3)).strftime("%d.%m.%Y %H:%M"),
     "deadline_hours": 0,
     "tracking_url": "https://kargotakip.araskargo.com.tr/",
     "reviews": []},
    {"id": "HB-44198", "platform": "Hepsiburada", "platform_color": "#6366F1",
     "product": "Hakiki Deri Ceket", "sku": "GY-101", "qty": 1, "total": 1849.00,
     "status": "Bekliyor", "customer": "Zeynep Arslan", "city": "İzmir",
     "district": "Konak", "address": "Alsancak Mah. No:22",
     "note": "",
     "cargo": "Yurtiçi Kargo", "tracking": None, "est_days": 2,
     "invoice": "INV-2026-0892", "commission": 0.14, "cargo_cost": 34.99, "kdv": 0.20,
     "date": (datetime.now() - timedelta(hours=5)).strftime("%d.%m.%Y %H:%M"),
     "deadline_hours": 43,
     "tracking_url": "https://www.yurticikargo.com/tr/",
     "reviews": []},
    {"id": "TY-99110", "platform": "Trendyol", "platform_color": "#F97316",
     "product": "Slim Fit Kot Pantolon — Mavi", "sku": "GY-220", "qty": 1, "total": 549.00,
     "status": "Bekliyor", "customer": "Emre Şahin", "city": "İstanbul",
     "district": "Şişli", "address": "Mecidiyeköy Mah. No:18",
     "note": "Akıllı kapıda teslim", "cargo": "Aras Kargo", "tracking": None, "est_days": 2,
     "invoice": "INV-2026-0893", "commission": 0.18, "cargo_cost": 29.99, "kdv": 0.20,
     "date": (datetime.now() - timedelta(hours=8)).strftime("%d.%m.%Y %H:%M"),
     "deadline_hours": 40,
     "tracking_url": "https://kargotakip.araskargo.com.tr/",
     "reviews": []},
    {"id": "HB-44280", "platform": "Hepsiburada", "platform_color": "#6366F1",
     "product": "Deri Cüzdan — Kahverengi", "sku": "AK-310", "qty": 1, "total": 379.00,
     "status": "Kargoda", "customer": "Selin Küçük", "city": "Antalya",
     "district": "Muratpaşa", "address": "Lara Cad. No:88",
     "note": "",
     "cargo": "PTT Kargo", "tracking": "PTT887766554", "est_days": 1,
     "invoice": "INV-2026-0888", "commission": 0.14, "cargo_cost": 22.50, "kdv": 0.20,
     "date": (datetime.now() - timedelta(days=2)).strftime("%d.%m.%Y %H:%M"),
     "deadline_hours": 18,
     "tracking_url": "https://gonderitakip.ptt.gov.tr/",
     "reviews": []},
    {"id": "TY-99125", "platform": "Trendyol", "platform_color": "#F97316",
     "product": "Pamuklu Banyo Havlu Seti", "sku": "EV-405", "qty": 1, "total": 449.00,
     "status": "Teslim Edildi", "customer": "Burcu Akın", "city": "Eskişehir",
     "district": "Tepebaşı", "address": "İstiklal Cad. No:33",
     "note": "",
     "cargo": "Aras Kargo", "tracking": "ARS445566778", "est_days": 0,
     "invoice": "INV-2026-0887", "commission": 0.18, "cargo_cost": 29.99, "kdv": 0.20,
     "date": (datetime.now() - timedelta(days=4)).strftime("%d.%m.%Y %H:%M"),
     "deadline_hours": 0,
     "tracking_url": "https://kargotakip.araskargo.com.tr/",
     "reviews": [{"user": "Burcu A.", "rating": 5,
                   "text": "Havlular çok yumuşak, teşekkürler!", "reply": None}]},
    {"id": "TY-98987", "platform": "Trendyol", "platform_color": "#F97316",
     "product": "İpek Desenli Fular — Lacivert", "sku": "AK-205", "qty": 2, "total": 638.00,
     "status": "İade", "customer": "Ali Çelik", "city": "İstanbul",
     "district": "Beşiktaş", "address": "Nispetiye Cad. No:5",
     "note": "Renk farklı geldi",
     "cargo": "Aras Kargo", "tracking": "ARS111222333", "est_days": 0,
     "invoice": "INV-2026-0878", "commission": 0.18, "cargo_cost": 29.99, "kdv": 0.20,
     "date": (datetime.now() - timedelta(days=5)).strftime("%d.%m.%Y %H:%M"),
     "deadline_hours": 0,
     "tracking_url": "https://kargotakip.araskargo.com.tr/",
     "reviews": [{"user": "Ali Ç.", "rating": 1,
                   "text": "Görseldeki renk ile ürün rengi tutmuyor!", "reply": None}]},
    {"id": "HB-44150", "platform": "Hepsiburada", "platform_color": "#6366F1",
     "product": "Klasik Beyaz Sneaker", "sku": "SN-014", "qty": 1, "total": 849.00,
     "status": "İade", "customer": "Hasan Yıldırım", "city": "Konya",
     "district": "Selçuklu", "address": "Yeni Meram Cad. No:9",
     "note": "Beden uymadı",
     "cargo": "MNG Kargo", "tracking": "MNG998877665", "est_days": 0,
     "invoice": "INV-2026-0860", "commission": 0.14, "cargo_cost": 24.99, "kdv": 0.20,
     "date": (datetime.now() - timedelta(days=7)).strftime("%d.%m.%Y %H:%M"),
     "deadline_hours": 0,
     "tracking_url": "https://www.mngkargo.com.tr/",
     "reviews": [{"user": "Hasan Y.", "rating": 2,
                   "text": "Beden tablosu yanlış, kalıbı küçük.", "reply": None}]},
]

MONTHS = ["Oca", "Şub", "Mar", "Nis", "May", "Haz", "Tem", "Ağu", "Eyl", "Eki", "Kas", "Ara"]
REVENUE  = [48500, 52300, 45800, 61200, 67800, 72400, 89500, 78300, 65400, 82100, 98700, 142500]
EXPENSES = [18200, 19800, 17400, 23100, 25600, 27300, 33800, 29600, 24700, 31000, 37300, 53800]
PROFIT   = [r - e for r, e in zip(REVENUE, EXPENSES)]

EXPENSE_BREAKDOWN = {
    "Platform Komisyonu": 21375,
    "Kargo Gideri":       14850,
    "Reklam (Ads)":        9500,
    "İade Zararı":         4200,
    "Vergi & KDV":         7150,
    "Depo & Ambalaj":      3200,
    "Diğer":               1525,
}

TRANSACTIONS = [
    {"date": "16.05.2026", "desc": "Trendyol Hakediş",        "type": "Gelir", "amount":  12450.0, "cat": "Pazar Yeri"},
    {"date": "15.05.2026", "desc": "Hepsiburada Hakediş",     "type": "Gelir", "amount":   8320.0, "cat": "Pazar Yeri"},
    {"date": "15.05.2026", "desc": "Aras Kargo Faturası",     "type": "Gider", "amount":  -1840.0, "cat": "Kargo"},
    {"date": "14.05.2026", "desc": "Trendyol Reklam",         "type": "Gider", "amount":  -2500.0, "cat": "Reklam"},
    {"date": "14.05.2026", "desc": "Sneaker İade Zararı",     "type": "Gider", "amount":   -850.0, "cat": "İade"},
    {"date": "13.05.2026", "desc": "Trendyol Hakediş",        "type": "Gelir", "amount":   9800.0, "cat": "Pazar Yeri"},
    {"date": "13.05.2026", "desc": "Ambalaj Malzemesi",       "type": "Gider", "amount":   -320.0, "cat": "Depo"},
    {"date": "12.05.2026", "desc": "Hepsiburada Reklam",      "type": "Gider", "amount":  -1200.0, "cat": "Reklam"},
    {"date": "11.05.2026", "desc": "Trendyol Hakediş",        "type": "Gelir", "amount":  15600.0, "cat": "Pazar Yeri"},
    {"date": "10.05.2026", "desc": "MNG Kargo Faturası",      "type": "Gider", "amount":   -980.0, "cat": "Kargo"},
    {"date": "09.05.2026", "desc": "Deri Ceket İade",         "type": "Gider", "amount":  -1849.0, "cat": "İade"},
    {"date": "09.05.2026", "desc": "Hepsiburada Hakediş",     "type": "Gelir", "amount":   6780.0, "cat": "Pazar Yeri"},
]

UPCOMING_PAYOUTS = [
    {"platform": "Trendyol",    "amount": 12450.0, "date": "17.05.2026", "color": "#F97316"},
    {"platform": "Hepsiburada", "amount":  8320.0, "date": "19.05.2026", "color": "#6366F1"},
]

MARKETPLACES = [
    {"name": "Trendyol", "active": True, "color": "#F97316",
     "revenue": 92400.0, "profit": 32000.0, "commission": 0.18,
     "return_rate": 0.04, "orders": 847, "rating": 4.8,
     "active_listings": 124, "buy_box_share": 0.62, "avg_basket": 218.0,
     "click_through": 0.038, "conversion": 0.067,
     "ad_spend_monthly": 3500.0, "organic_share": 0.71,
     "desc": "Türkiye'nin en büyük e-ticaret platformu",
     "join_steps": [
        ("Mağaza Başvurusu",        "Trendyol Partner sayfasından başvuru. 1-2 iş günü."),
        ("Vergi & Belge Onayı",     "Vergi levhası, IBAN, faaliyet belgesi yüklemesi. 2-3 iş günü."),
        ("Komisyon Sözleşmesi",     "Kategori komisyon oranı %15-22 arası. E-imza."),
        ("Mağaza Açılışı",          "Onaylı ürünler 24 saat içinde yayına giriyor."),
     ],
     "avg_unlock_days": 7},
    {"name": "Hepsiburada", "active": True, "color": "#6366F1",
     "revenue": 50100.0, "profit": 16200.0, "commission": 0.14,
     "return_rate": 0.07, "orders": 312, "rating": 4.6,
     "active_listings": 98, "buy_box_share": 0.48, "avg_basket": 161.0,
     "click_through": 0.029, "conversion": 0.048,
     "ad_spend_monthly": 1800.0, "organic_share": 0.84,
     "desc": "Türkiye'nin köklü e-ticaret platformu",
     "join_steps": [
        ("Mağaza Başvurusu",        "Hepsiburada Partner portalı üzerinden. 1 iş günü."),
        ("Vergi & Belge Onayı",     "Belge yüklemesi. 2 iş günü."),
        ("Komisyon Sözleşmesi",     "Kategori komisyonu %10-18."),
        ("Mağaza Açılışı",          "Listeleme sonrası 12 saat içinde aktif."),
     ],
     "avg_unlock_days": 5},
    {"name": "Amazon TR/EU", "active": False, "color": "#F59E0B",
     "unlock_fee": "Aylık 39.99 USD (Professional Plan)",
     "listing_fee": "Ürün başına ortalama 0.99 USD + %8-15 referans ücreti",
     "potential": "Yüksek",
     "ai_note": "Ürünlerinizin Avrupa pazarında rekabet şansı yüksek. "
                "FBA modeli ile lojistiği devredebilirsiniz. Tahmini 6 ayda yatırım geri dönüşü pozitif.",
     "desc": "Global pazar, FBA depo imkânı",
     "join_steps": [
        ("Hesap Kaydı",             "Amazon Seller Central, kurumsal hesap. Aynı gün."),
        ("Banka & Vergi Bilgileri", "Amerikan vergi formu W-8BEN. 1-2 hafta."),
        ("Kimlik & Belge Onayı",    "Kimlik doğrulama, fatura, işletme belgesi. 5-10 iş günü."),
        ("FBA Yerleşimi",           "Ürünleri Almanya/Polonya FBA deposuna gönderme. 2-4 hafta."),
        ("Mağaza Aktivasyonu",      "Listeleme onayı sonrası yayına giriş."),
     ],
     "avg_unlock_days": 35,
     "expected_revenue_lift": 0.40, "expected_profit_lift": 0.28},
    {"name": "Etsy", "active": False, "color": "#F87171",
     "unlock_fee": "Listeleme başına 0.20 USD",
     "listing_fee": "%6.5 işlem komisyonu + %3 + 0.25 USD ödeme işlem ücreti",
     "potential": "Orta",
     "ai_note": "El yapımı ve tasarım ürünler için ideal. Mevcut hazır giyim "
                "portföyünüz için ROI düşük olabilir. Aksesuar yatırımı önerilir.",
     "desc": "El emeği ve tasarım ürünler için global pazar",
     "join_steps": [
        ("Mağaza Kaydı",            "Etsy.com üzerinden kayıt. Aynı gün."),
        ("Ödeme Hesabı",            "PayPal/Payoneer bağlantısı. 1-3 gün."),
        ("Mağaza Açılışı",          "İlk ürün listeleme sonrası 24 saat içinde aktif."),
     ],
     "avg_unlock_days": 3,
     "expected_revenue_lift": 0.08, "expected_profit_lift": 0.04},
    {"name": "N11", "active": False, "color": "#8B5CF6",
     "unlock_fee": "Ücretsiz mağaza kaydı",
     "listing_fee": "%8-14 kategori bazlı komisyon",
     "potential": "Orta",
     "ai_note": "Düşük komisyon avantajlı; ancak organik trafik Trendyol'un %20'si "
                "seviyesinde. Reklam bütçesi gerektirir.",
     "desc": "Türkiye pazarı, düşük komisyon oranları",
     "join_steps": [
        ("Mağaza Başvurusu",        "N11.com Mağaza Aç üzerinden. 1 iş günü."),
        ("Belge Onayı",             "Vergi levhası, IBAN. 2-3 iş günü."),
        ("Mağaza Açılışı",          "Onay sonrası anlık aktif."),
     ],
     "avg_unlock_days": 4,
     "expected_revenue_lift": 0.15, "expected_profit_lift": 0.10},
]

ADVISOR_INSIGHTS = [
    {"type": "danger", "severity": 9,
     "title": "İade Riski: SN-014 Klasik Beyaz Sneaker",
     "body": "Son 7 günde iade oranı %15'e yükseldi (normal: %4). İade notlarında 'kalıbı dar' ve "
             "'beden uymadı' ifadeleri tespit edildi. Ürün açıklamasına 'Bir numara büyük alın' ibaresi "
             "ekleyin ve görselleri güncelleyin. Tahmini yıllık tasarruf: 12.600 TL.",
     "action": "Açıklamayı Güncelle", "target_sku": "SN-014"},
    {"type": "warning", "severity": 8,
     "title": "Kritik Stok: SN-014 ve GY-101",
     "body": "SN-014 Klasik Beyaz Sneaker (12 adet) emniyet stoğu altında. Talep tahminine göre 4 gün "
             "içinde stok tükenecek. (s,Q) politikasına göre 50 adet sipariş öneriliyor (19.000 TL). "
             "GY-101 Deri Ceket için 30 adet sipariş (21.600 TL).",
     "action": "Sipariş Oluştur", "target_sku": "SN-014"},
    {"type": "info", "severity": 6,
     "title": "Kurban Bayramı Fırsatı — 20 Haziran",
     "body": "Bayrama 35 gün kaldı. Geçmiş verilere göre giyim kategorisi bayram öncesi 10. günde "
             "%45 satış artışı yaşıyor. Bugün %10 indirim kampanyası başlatın. Tahmini ciro artışı: "
             "%32, net kâr artışı: %18.",
     "action": "Kampanya Oluştur", "target_sku": None},
    {"type": "success", "severity": 5,
     "title": "TS-001 Premium Tişört: En Yüksek Kârlılık",
     "body": "TS-001 ürününüz bu ay %194 ROI ile portföyünüzün en kârlı ürünü. Trendyol'da organik "
             "sırada 3. konumdasınız. Reklam bütçesini bu ürüne yönlendirin.",
     "action": "Raporu Gör", "target_sku": "TS-001"},
    {"type": "warning", "severity": 7,
     "title": "Kargo Konsolidasyon Fırsatı",
     "body": "Bugün aynı adrese (İstanbul/Kadıköy) giden 2 farklı sipariş tespit edildi. Tek kargoya "
             "birleştirilmesinde 45 TL tasarruf edilebilir.",
     "action": "Birleştir", "target_sku": None},
    {"type": "warning", "severity": 7,
     "title": "Tedarikçi Uyarısı: İzmir Ayakkabı Ltd.",
     "body": "Son 3 sipariş ortalama 2.1 gün geç geldi (zamanlılık %78). Defekt oranı %4.5. "
             "Alternatif tedarikçi arayışı önerilir. Geç teslim nedeniyle yaklaşık 3.200 TL kazanç "
             "kaybı yaşandı.",
     "action": "Alternatif Bul", "target_sku": "SN-014"},
]

PROFILE = {
    "company_name": "EaaS Teknoloji A.Ş.",
    "trade_name":   "Auto-Commerce OS",
    "tax_office":   "Bursa Vergi Dairesi",
    "tax_no":       "1234567890",
    "mersis_no":    "0123456789012345",
    "address":      "Kestel Mah. Organize Sanayi Bölgesi No:12",
    "city":         "Bursa",
    "district":     "Kestel",
    "zip":          "16400",
    "phone":        "+90 224 555 0001",
    "email":        "info@eaas-os.com",
    "website":      "www.eaas-os.com",
    "founder": "",
    "founded":      "2024",
    "employees":    "5",
    "sector":       "Teknoloji & E-Ticaret",
    "iban":         "TR12 0001 0000 0000 0000 0000 00",
    "bank":         "Garanti BBVA",
}
